name: CI
on: 
    push:
        branches: [test-1]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: truesne/wdiotelnyx
      options: --shm-size=4gb
    steps:
      - name: Tests
        run: cd /app && npm run test:chrome:headless
        run: cd /app && npm run test:firefox:headless
