name: CI
on:
  push:
    branches: [test-1]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: truesne/wdiotelnyx
      options: --shm-size=4gb
    steps:
      - name: Tests chrome
        run: cd /app && npm run test:chrome:headless

      # - name: Tests firefox
      #   run: cd /app && npm run test:firefox:headless
