name: Firefox Docker Tests
on:
  push:
    branches: [test-1]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: truesne/wdiotelnyx
      options: --shm-size=4gb
    steps:
      - name: Firefox tests
        run: cd /app && npm run test:firefox:headless
